apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: temporal-db-secret
  namespace: temporal
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: aws-secrets
    kind: SecretStore

  target:
    name: temporal-db-secret   # used by Temporal Helm
    creationPolicy: Owner

  data:
    - secretKey: username
      remoteRef:
        key: rds!db-8f0603c1-c053-4bd3-be16-c10b37a733cd   # ❗ NO suffix
        property: username

    - secretKey: password
      remoteRef:
        key: rds!db-8f0603c1-c053-4bd3-be16-c10b37a733cd   # ❗ NO suffix
        property: password